# -*- coding: utf-8 -*-
"""Study Assistant.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uI7G2ar1UoQj5lswG9YKs3SP90i8bLaG
"""

# ✅ Install dependencies
!pip install langchain langchain-google-genai PyPDF2 fpdf

# ✅ Imports
import os
import PyPDF2
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain.prompts import PromptTemplate
from fpdf import FPDF

# ✅ Set Gemini API key
os.environ["GOOGLE_API_KEY"] = ""  # ← Replace this with your real key

# ✅ Initialize Gemini LLM
llm = ChatGoogleGenerativeAI(model="gemini-1.5-flash", temperature=0.3)

# ✅ Load study content from PDF
def load_pdf_text(file_path):
    with open(file_path, "rb") as f:
        reader = PyPDF2.PdfReader(f)
        text = ""
        for page in reader.pages:
            text += page.extract_text()
    return text

# ✅ Summarize the content
def summarize_content(text):
    prompt = f"Summarize the following study material into concise bullet points:\n\n{text}\n\nSummary:"
    return llm.invoke(prompt)

# ✅ Generate MCQ quiz questions
def generate_quiz(summary):
    prompt_template = PromptTemplate.from_template(
        "Based on the following summary, generate 2 multiple-choice questions with 4 options each. Provide the correct answer after each question:\n\n{summary}\n\nFormat:\nQ: <question>\nA. Option A\nB. Option B\nC. Option C\nD. Option D\nAnswer: <correct option letter and text>"
    )
    return llm.invoke(prompt_template.format(summary=summary))

# ✅ Save results to PDF
def save_to_pdf(summary, quiz, output_path="study_assistant_output.pdf"):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    pdf.set_font("Arial", 'B', 14)
    pdf.cell(0, 10, "Study Assistant - Summary & Quiz", ln=True, align="C")

    pdf.set_font("Arial", 'B', 12)
    pdf.cell(0, 10, "Summary", ln=True)
    pdf.set_font("Arial", '', 11)
    for line in summary.split("\n"):
        pdf.multi_cell(0, 10, line)

    pdf.ln(5)
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(0, 10, "Quiz Questions", ln=True)
    pdf.set_font("Arial", '', 11)
    for line in quiz.split("\n"):
        pdf.multi_cell(0, 10, line)

    pdf.output(output_path)
    return output_path

# ✅ Upload PDF
from google.colab import files
uploaded = files.upload()
pdf_path = list(uploaded.keys())[0]

# ✅ Process
study_text = load_pdf_text(pdf_path)
summary = summarize_content(study_text).content
quiz = generate_quiz(summary).content
pdf_file = save_to_pdf(summary, quiz)

# ✅ Downloadable Output
files.download(pdf_file)
